name: Concurrent

on:
    workflow_dispatch: 

concurrency: 
    group: 'concurrent'
    cancel-in-progress: true

jobs:
    queue:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/github-script@v7
            with:
                script: |
                    const sleep = (min) => new Promise((resolve) => setTimeout(resolve, min * 1000 * 60));
                    await sleep(5);