name: Concurrent

on:
    workflow_dispatch: 

concurrency: 
    group: 'concurrent'
    cancel-in-progress: true

jobs:
    queue:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/github-script@v3
            with:
                script: |
                    console.log('It works')