name: Queued

on:
    workflow_dispatch: 

jobs:
    queue:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/github-script@v3
            with:
                script: |
                    console.log('It works')