name: Queued

on:
    workflow_dispatch: 

jobs:
    queue:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/github-script@v7
            with:
                script: |
                    const sleep = (sec) => new Promise((resolve) => setTimeout(resolve, sec * 1000));
                    await sleep(60);