name: Queued

on:
    workflow_dispatch: 

jobs:
    queue:
        runs-on: ubuntu-latest
        steps:
          - uses: ahmadnassri/action-workflow-queue@v1
          - uses: actions/github-script@v7
            with:
                script: |
                    const sleep = (min) => new Promise((resolve) => setTimeout(resolve, min * 1000 * 60));
                    await sleep(5);